apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: spark-test1
spec:
  type: Python
  sparkVersion: 3.5.1
  mode: cluster
  image: lr1-bd-harbor-registry.mip.storage.hpecorp.net/develop/gcr.io/mapr-252711/spark-3.5.1:v3.5.1.0.5
  imagePullPolicy: Always
  imagePullSecrets:
  - imagepull
  spec:
    deps:
      jars:
        - local:///mounts/shared-volume/shared/spark/openlineage-spark_2.12-1.23.0.jar
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///mounts/shared-volume/shared/spark/test2.py"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.1
    volumeMounts:
      - name: shared-volume
        mountPath: /mounts/shared-volume/shared
  executor:
    cores: 1
    instances: 2
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.1
    volumeMounts:
      - name: shared-volume
        mountPath: /mounts/shared-volume/shared
    volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: kubeflow-shared-pvc
